-- Add rating columns to orders table
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS rating_restaurant INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rating_food INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rating_service INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS rating_comment TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_rated BOOLEAN DEFAULT FALSE;
